# Generated by Django 3.0.7 on 2020-06-04 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sound', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='soundpost',
            name='image',
            field=models.ImageField(default='default.png', upload_to='images'),
        ),
    ]
