# Generated by Django 3.0.7 on 2020-06-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sound', '0003_soundpost_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soundpost',
            name='image',
            field=models.ImageField(default='images/default.png', upload_to='images'),
        ),
    ]
