# Generated by Django 2.2.12 on 2020-06-05 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sound', '0006_soundpost_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soundpost',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
