# Generated by Django 2.2.12 on 2020-06-05 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sound', '0009_auto_20200605_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soundpost',
            name='author',
        ),
    ]
