# Generated by Django 2.2.12 on 2020-06-11 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sound', '0013_auto_20200605_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soundpost',
            name='title',
            field=models.CharField(max_length=23),
        ),
    ]
