# Generated by Django 2.2.12 on 2020-06-11 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sound', '0016_auto_20200611_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='soundpost',
            name='adds',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='soundpost',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
